### ISSUE TITLE
Can you explain how to use this?

### ISSUE THREAD

**Issue by shady2k** [m42e/mayan-automatic-metadata#1]
1. Need cron to execute script?
2. Can you explain plugin content? How does it works?
3. Will I create new user to interract with mayam?

**Comment by m42e** [comment]
1. You currently have to trigger it manually
2. A Plugin tests certain criteria. it it matches it tries to add some metadata.
3. That is up to you. you can use an existing user, too.

**Comment by m42e** [comment]
I'm also having a version which could be triggered by mayan. I will upload this one in a week or two.

**Comment by shady2k** [comment]
Thank you
